[phases.setup]
nixPkgs = ["nodejs", "python3", "pkg-config", "cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg", "pixman", "fontconfig", "freetype"]
aptPkgs = ["fonts-dejavu-core", "fonts-liberation"]
